// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYf6bJU9Z-Sq1iY7iKXTyN_eKH4yj7ggk',
    appId: '1:553728888135:web:0dc97615afd0b56708d062',
    messagingSenderId: '553728888135',
    projectId: 'fandag-app',
    authDomain: 'fandag-app.firebaseapp.com',
    storageBucket: 'fandag-app.firebasestorage.app',
    measurementId: 'G-730W951K5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOUqHbB97TuRsLPmUFUvObVVrP877sOg',
    appId: '1:553728888135:android:a46a0d2b7cd238e408d062',
    messagingSenderId: '553728888135',
    projectId: 'fandag-app',
    storageBucket: 'fandag-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPc_i4wKrg3aK77zKZm8Tb_LOo-1i4gM',
    appId: '1:553728888135:ios:2d4c5d9fbffc669d08d062',
    messagingSenderId: '553728888135',
    projectId: 'fandag-app',
    storageBucket: 'fandag-app.firebasestorage.app',
    iosBundleId: 'ru.madbrains.template',
  );
}
